### PR TITLE
fix array decoding

### LINKED ISSUE #247: Crash in ABI-decoder
The function `ContractCallDataEncoder::decodeArray` accesses values in the data array without proper size checking. If the data array is not large enough, it should either fail or assume the values are zero.

Reported by @JohnDorien1

### PR DESCRIPTION
**Pull request by yann300**
fixes https://github.com/ethereum/mix/issues/247

### CODE REVIEW

**Comment by chriseth** [comment]
This might fix the reported crash, but please also make `ContractCallDataEncoder::decodeArray` more robust to invalid input data.

File: src/ClientModel.cpp [hunk 1]
```diff
@@ -1201,7 +1202,6 @@ void ClientModel::onNewTransaction(RecordLogEntry::TxSource _source)
 						{
 							bytes data;
 							QVariant param;
-							u256 pos = 0;
 							if (!e->isIndexed())
 								param = encoder.decodeType(e->type()->type(), log.data, pos);
 							else
```
Comment (chriseth) [inline src/ClientModel.cpp:1207]: I think pos should be zero for the case of indexed data (below).

File: src/ContractCallDataEncoder.cpp [hunk 2]
```diff
@@ -312,6 +312,8 @@ QJsonArray ContractCallDataEncoder::decodeArray(SolidityType const& _type, bytes
 	if (_type.type == QSolidityType::Type::Bytes || _type.type == QSolidityType::Type::String)
 	{
 		bytesConstRef value(_value.data() + (static_cast<size_t>(offset) + 32), static_cast<size_t>(count));
+		if (value.size() < count)
```
Comment (chriseth) [inline src/ContractCallDataEncoder.cpp]: There are more like these above. Actually every time you create a `bytesConstRef`.

File: src/ClientModel.cpp (hunk 1 above)
Comment (yann300) [inline src/ClientModel.cpp:1207]: right

File: src/ContractCallDataEncoder.cpp [hunk 3]
```diff
@@ -382,6 +389,8 @@ QVariant ContractCallDataEncoder::decodeRawArray(SolidityType const& _type, byte
 		value.populate(&rawParam);
```
Comment (chriseth) [inline src/ContractCallDataEncoder.cpp:389]: If I see that correctly, then two lines above you create a bytesConstRef that can span 32 bytes beyond the end of the byte array, and there are similar cases elsewhere.

Comment (yann300) [inline src/ContractCallDataEncoder.cpp:389]: I've noticed that. The test above (line 375) is here to prevent to continue if "pos" is really important. 
What I saw is that when the memory is in an intermediate state "pos" could be really huge, this test was enough to prevent a crash in that case. 
but I guess I should be more precise you're right.
